### ISSUE TITLE
transfer to remotestorage organization?

### ISSUE THREAD

**Issue by jancborchardt** [jcoglan/restore#1]
As mentioned on the [new remotestorage mailing list](http://librelist.com/browser/remotestorage/2012/9/12/remotestorage-separation-from-unhosted/#da34bc32ac02c7628cf05174a8c2c946), it would probably be good to have the repositories of the different actively maintained implementations under one umbrella.

Do you prefer having it under your own name or do you want to transfer it to the remotestorage Github organization?

(Btw, we have a sweet new site: http://remotestorage.io )

**Comment by jcoglan** [comment]
I'm closing this since I plan to keep this project under my control. However I intend to maintain compatibility with RemoteStorage.js and keep up with protocol updates, while maintaining backward compatibility where I can.

I always appreciate PRs from users, especially to incorporate spec updates. Which reminds me, @silverbucket  -- did you have more PRs to come or should I roll out a 0.3 release? I'm meaning to give the latest spec a read before I do that, but it seems to work with the 0.11 client.

**Comment by untitaker** [comment]
@jcoglan You don't appear to have the time and/or interest for this project anymore. Would you reconsider a transfer?

**Comment by jcoglan** [comment]
@untitaker I've had various questions to this effect and so I've written something to explain where I am: https://gist.github.com/jcoglan/2e0daf58a165ffdc8f21

**Comment by untitaker** [comment]
@jcoglan 

Thanks for this explanation.

You seem to assume that moving reStore to the remotestorage organization would require reStore to become a complex general-purpose server. Personally I had rather some form of maintenance-mode in mind, where reStore gets a feature-freeze, you get to become some sort of BDFL, but at the same time, we remove the dependency on the only maintainer -- you -- to do things like fixing bugs. I think this is important because bugs like #37 are rather critical (not only to me) -- at the same time you, of course, don't owe anybody a fix or response.

The next-best idea that comes to mind is you adding more maintainers. This would also avoid the problem of depriving you from credit by keeping the project on your GH account.

**Comment by untitaker** [comment]
@jcoglan Could we talk about this in `#remotestorage` on Freenode?

**Comment by untitaker** [comment]
Please take at least the time to _discuss_ this issue. Your text brought up more questions than it answered, and while nobody expects a _solution_ from you, having two "active" projects named "restore" is far from being one.
