### ISSUE TITLE
Initial user signup

### ISSUE THREAD

**Issue by clark800** [jcoglan/restore#16]
It would be convenient if there was an option to allow user signup only if no users exist. Then I could do the initial user registration through the website and not have to worry about other users registering afterwards.

**Comment by jcoglan** [comment]
I don't feel great about adding an option like this since it makes the behaviour implicit and non-obvious, and allows race conditions. I think the user should opt in explicitly to allowing sign-ups on their server, and I should document that as you suggested in https://github.com/jcoglan/restore/issues/18.
