### ISSUE TITLE
Update release version

### ISSUE THREAD

**Issue by skddc** [jcoglan/restore#34]
Apparently a lot of people running into reStore being broken out of the box when installing from npm (the template variable issue that was fixed since then).

@jcoglan Would be great if you could bump the version and publish the current master on npm real quick.

**Comment by jcoglan** [comment]
I'm really sorry this has gone so long without a release. I keep meaning to get to it but other projects and commitments keep taking up my time.

I have just closed releases on a bunch of other projects and getting reStore back to health is now top of my list. I'm moving house shortly (that's one thing that's been sapping my time this year) so I might be without internet, but I'll do what I can.

I can't release `master` as-is because there's still work in progress that I never quite got finished off, and keep forgetting the details of because of context switching. I'm now trying to get my brain back into RemoteStorage, starting by drawing up [some notes](https://github.com/jcoglan/restore/blob/master/PROTOCOL.md) on spec versions so I know what's going on and can figure out what to release.

In the interim I recommend people install from git rather than me doing an actual release.

**Comment by skddc** [comment]
Thanks for the update!

Maybe it'd be a good idea to put a note at the beginning of the README for installing from Git then.

That document about the spec versions is excellent! We recently set up a wiki, which is not used much yet (or linked or advertised anywhere) for exactly this kind of content. If you like, drop your stuff in there too (random page name is totally fine): https://wiki.remotestorage.io/

**Comment by jcoglan** [comment]
I will shortly be releasing 0.3.0 from `master`. I'm sorry it took so long; the last month or so has been full of house-moving stuff, packing, making the new place liveable, and so on. In fact I just got internet last week.

I will try to respond more quickly to things in future, and getting all the stuff I've been sitting on for a year+ released ought to help with this. Thanks for the nudge :)

**Comment by jcoglan** [comment]
0.3.0 has now been released, cc @silverbucket @michielbdejong

**Comment by jcoglan** [comment]
Gosh it has been a while... this release includes the changes that prompted this article from June last year... https://blog.jcoglan.com/2014/06/16/graphical-thinking-optimisation-through-functional-programming/

I've had a pattern of starting things that turn out to be a lot of work and then not having time to finish them in the last 12 months, I guess. There's still a bunch of work I want to do on reStore to get to draft-02 and beyond, and I have ideas for how to do that, but not the time, at the moment. I might be more available from the end of September.

**Comment by raucao** [comment]
Thanks!
